### ISSUE TITLE
Чат гостьовій румі

### ISSUE THREAD

**Issue by paulandroshchuk** [andrewshostak/prognoz_v2_angular#1]
Все вліплено в один блок (ім'я, повідомлення і дата, думаю доцільно булоб зробити якісь <hr> чи ще щось в цьому роді, щоб чітко відокремити повідомленя

https://db.tt/qmATcTVR6V

**Comment by andrewshostak** [comment]
@paulandroshchuk 
Виправлено:
https://github.com/andrewshostak/prognoz_v2_angular/commit/96413afa37af6e5500f1713ff9e6538468fa7081
