### ISSUE TITLE
Вага аплікухі

### ISSUE THREAD

**Issue by paulandroshchuk** [andrewshostak/prognoz_v2_angular#2]
3.2 MB це дуже багато, можна білдити під продакшин і білдити за допомогою Ahead Of Time
https://db.tt/sQCWpgeOFA

**Comment by andrewshostak** [comment]
Розмір js-файлів зменшено з 2300кб до 397кб за допомогою включення модуля стискання файлів веб сервера. Сумарний розмір при цьому зменшений з 3.2мб до 1.1мб. В майбутньому ще зменшу розмір зображень.
