### ISSUE TITLE
Важкочитабельний тип дати

### ISSUE THREAD

**Issue by paulandroshchuk** [andrewshostak/prognoz_v2_angular#4]
https://db.tt/YJ3jVNDXnh - незнаю як кому, но особисто мені таки тип дати дуже важко читається, думаю булоб краще зробити тип "Difference for Humans"

**Comment by andrewshostak** [comment]
@paulandroshchuk 
https://github.com/andrewshostak/prognoz_v2_angular/commit/13f508b57b55c50abd24bf6e191765be6da71ae0
Тепер всі дати в форматі, який нормально читається.
