### ISSUE TITLE
Сторінка профілю

### ISSUE THREAD

**Issue by paulandroshchuk** [andrewshostak/prognoz_v2_angular#6]
https://db.tt/YGipG2ynFP

1. Незрозуміла інформація, просто логін і дата в важкочитабельному стилі
2. Аватарка, 2017 рік не дворі, і використовується звичайний input з типом file.. )) можна щось придумати щоб краще виглядало
3. Кнопка 'Зберегти зміни' знаходиться в не зрозумілому місці, трошкі правіше центра
4. Блоки для оновлення фото і персональних даних знаходиться також не симетрично

**Comment by andrewshostak** [comment]
@paulandroshchuk 
Змінив вигляд сторінки профілю.
https://github.com/andrewshostak/prognoz_v2_angular/commit/603a1411624251a15b8d66c673fa512473643147
