### ISSUE TITLE
праве меню юзера

### ISSUE THREAD

**Issue by paulandroshchuk** [andrewshostak/prognoz_v2_angular#9]
https://db.tt/5uIq3snvUO

Думаю можна підключити dropdown, щоб не тулились біля себе кнопки, або зробити їх групування:
http://getbootstrap.com/components/#btn-groups

**Comment by andrewshostak** [comment]
@paulandroshchuk 
виправлено:
https://github.com/andrewshostak/prognoz_v2_angular/commit/8406740286584c0099aad247862d55dc3d5c7d6c
